#!/bin/sh
#

source ./build

#go run options.go -h
#go run options.go -d 6 -f -v -i 3 -s 7 -t 4 -m job-skills


#cd examples/amqp/pubsub
#go run pubsub.go

cd examples/amqp/simple-consumer
go run consumer.go

#cd examples/amqp/simple-producer
#go run producer.go
